### ISSUE TITLE
__init.__py file not recognized by Calibre

### ISSUE THREAD

**Issue by nicofricano** [Leseratte10/lcpl-calibre-plugin#1]
I tried to install the plugin in Calibre and this error was showed me:
```
calibre, version 5.31.1
ERRORE: Eccezione non gestita: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\nicod\\Downloads\\lcpl-calibre-plugin-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.31.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\nicod\\Downloads\\lcpl-calibre-plugin-master.zip' is invalid. It does not contain a top-level __init__.py file

```

**Comment by Leseratte10** [comment]
You tried to download the source code through the "Code" -> "Download ZIP" links on Github (or the "Source code" link on the Releases page). This will give you the plugin in source form, not ready to be installed. You need to go to https://github.com/Leseratte10/lcpl-calibre-plugin/releases and download the pre-packed ZIP file (currently LCPL.Input.v0.0.2.zip).

**Comment by Leseratte10** [comment]
Closing this issue as there's been no response. If this is still an issue even when downloading the plugin ZIP from the "Releases" page, please re-open / comment again.
