### ISSUE TITLE
cannot load plugin in Calibre 5.32

### ISSUE THREAD

**Issue by algreen702021** [Leseratte10/lcpl-calibre-plugin#2]
Hi,
cannot load plugin in Calibre 5.32   (Ubuntu 18.04)
I tried to load the full .zip and just the zipped calibre-plugin folder, same results.
Any help please?
Thanks Alex

```
calibre, version 5.32.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/tess/Downloads/lcpl-calibre-plugin-master/calibre-plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.32  embedded-python: True is64bit: True
Linux-5.4.0-91-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-91-generic', '#102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021')
Python 3.8.5
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/tess/Downloads/lcpl-calibre-plugin-master/calibre-plugin.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by Leseratte10** [comment]
Hi Alex, 
it looks like you downloaded the plugin through GitHub's code download function - that gives you the raw source code that's not packaged correctly for a calibre install. That's the same issue as in #1. Try going to the release page ( https://github.com/Leseratte10/lcpl-calibre-plugin/releases ), then download the "LCPL.Input.v0.0.5.zip" file and import that into Calibre without extracting, then it should work.

**Comment by algreen702021** [comment]
It works...nice, thanks   :)
